### PR TITLE
Fix setting allocator to NULL.

### LINKED ISSUE #477: rcutils_get_zero_initialized_string_array has (potential) data race
hello, during thread sanitizer test, I've found multi thread calling into rcutils_get_zero_initialized_string_array gives data race warnings from thread sanitizer

https://github.com/ros2/rcutils/blob/rolling/src/string_array.c#L35

```c
rcutils_string_array_t
rcutils_get_zero_initialized_string_array(void)
{
  static rcutils_string_array_t array = {
    .size = 0,
    .data = NULL,
  };
  array.allocator = rcutils_get_zero_initialized_allocator();  //.  <---- thread sanitizer report data race this line because caller on some other thread may read it, but every threading running this line is write to it, without synchronize
  return array;
}
```
this may behave correctly on some architect, but still a data race in C standard

### PR DESCRIPTION
**Pull request by clalancette**
That is, previously the code was setting the allocator at runtime, not during static initialization.  Switch to static initialization, which should fix a possible race.

This should fix #477 .

A draft until we get confirmation from the reporter that it fixes the issue.

### CODE REVIEW

**Comment by clalancette** [comment]
Pulls: https://github.com/ros2/rcutils/pull/478
Gist: https://gist.githubusercontent.com/clalancette/0d8c51702f95917fc2b7fdbafa436af3/raw/e7af239fbc2785887fc1e6ee1f32787191ab063f/ros2.repos
BUILD args:  --packages-above-and-dependencies rcutils
TEST args:  --packages-above rcutils
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14537
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21813/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16084/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1316/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22514/)

**Review by fujitatomoya — COMMENTED** [review]
@clalancette i agree with you, this should fix the warning.

if this works, can we also apply the same patch for `rcutils_get_zero_initialized_char_array` and `rcutils_get_zero_initialized_uint8_array`?

**Comment by clalancette** [comment]
> if this works, can we also apply the same patch for `rcutils_get_zero_initialized_char_array` and `rcutils_get_zero_initialized_uint8_array`?

Good call.  I also found that `rcutils_get_zero_initialized_shared_library` didn't use this pattern at all, so I've now converted it over as well.  With that done, and confirmation that this fixes the sanitizer, I'm going to switch this to a "real" PR and run full CI on it.

**Comment by clalancette** [comment]
Pulls: https://github.com/ros2/rcutils/pull/478
Gist: https://gist.githubusercontent.com/clalancette/f02ff4e3f3fc6d8241350f341deeea9f/raw/e7af239fbc2785887fc1e6ee1f32787191ab063f/ros2.repos
BUILD args:  --packages-above-and-dependencies rcutils
TEST args:  --packages-above rcutils
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14544
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21821/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16091/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1323/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22521/)

**Review by fujitatomoya — APPROVED** [review]
lgtm!

File: src/char_array.c [hunk 1]
```diff
@@ -25,9 +25,15 @@ rcutils_get_zero_initialized_char_array(void)
...
+    .buffer_capacity = 0u,
+    .allocator = {
+      .allocate = NULL,
+      .deallocate = NULL,
+      .reallocate = NULL,
+      .zero_allocate = NULL,
+      .state = NULL
+    }
   };
-  char_array.allocator = rcutils_get_zero_initialized_allocator();
```
Comment (fujitatomoya) [inline src/char_array.c:30]: @clalancette i may be mistaken but i was thinking that maybe we should use stack memory and call `rcutils_get_zero_initialized_allocator`? i think this is not good approach for the structure maintenance. please see https://github.com/ros2/rmw/pull/378#discussion_r1751214891 too.

**Review by fujitatomoya — CHANGES_REQUESTED** [review]

File: src/char_array.c (hunk 1 above)
Comment (fujitatomoya) [reply src/char_array.c:30]: okay, i think having all members static variable can work the most effectively.

> The problem with doing it on the stack is that it reintroduces the race that we are originally trying to fix. In point of fact, that was exactly what the previous code did.

i was thinking a few things.

- specifying all member variables is not well-maintained code, this is already discussed above.
- remove `static` above, so that it can create the zero init structure with calling member specific zero init function in stack and then return the copy of that. this also should solve the racy condition. (compared to static initialization, this is less performance, but since this is initialization, i thought that was okay and we can rely on the each structure initialization call.)
- some member variables have `default` (not zero initialized) setting. the following code is actually initialized all 0, but having default setting (can be changed and updated in the future) in zero initialized call is mislead. So i think this is another issue.

https://github.com/ros2/rmw/blob/ac4f9afccca3dc305f2b519fdb0fb9131250f2a5/rmw/src/init_options.c#L35

Comment (clalancette) [reply src/char_array.c:30]: > * remove `static` above, so that it can create the zero init structure with calling member specific zero init function in stack and then return the copy of that. this also should solve the racy condition. (compared to static initialization, this is less performance, but since this is initialization, i thought that was okay and we can rely on the each structure initialization call.)

Ah, I see, I misunderstood your previous comment.  Yeah, doing it as a stack variable would fix both the thread problems and make it still work.  Since we've used the static initialization to this point, I'd prefer to just keep using that, but I don't feel that strongly about it.

> * some member variables have `default` (not zero initialized) setting. the following code is actually initialized all 0, but having default setting (can be changed and updated in the future) in zero initialized call is mislead. So i think this is another issue.

Yeah, agreed.  That looks like a bug.

Comment (methylDragon) [reply src/char_array.c:30]: I'd prefer static for performance reasons, especially since these structs and data types get used a ton everywhere.

Comment (clalancette) [reply src/char_array.c:30]: Yeah, agreed with @methylDragon here.

With that all said, I think I just need an approval on this now, and I can go ahead and merge it.  Thanks!

**Review by fujitatomoya — APPROVED** [review]
thanks for advice, lgtm.

**Comment by clalancette** [comment]
The latest CI here was successful (the yellow builds were known flakes).  Given that, I'm going to go ahead and merge, thanks everyone!

**Comment by clalancette** [comment]
Actually, arg.  I'm very sorry.  We agreed to put this in the BSS via *not* specifying all of the fields.  Thus, I'm actually going to change this to get rid of the explicit initialization.  Changes upcoming.

**Comment by clalancette** [comment]
Pulls: https://github.com/ros2/rcutils/pull/478
Gist: https://gist.githubusercontent.com/clalancette/a386de13a9a1af1cc5804a72f192a0c1/raw/e7af239fbc2785887fc1e6ee1f32787191ab063f/ros2.repos
BUILD args:  --packages-above-and-dependencies rcutils
TEST args:  --packages-above rcutils
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14556
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21833/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16103/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1335/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22541/)

**Review by fujitatomoya — APPROVED** [review]
lgtm with green CI

**Comment by clalancette** [comment]
Hm, the failures here are ones I haven't seen before.  So I'm going to have to look at it closer.

**Comment by clalancette** [comment]
This has actually exposed a bug in rcl.  I'll open up a PR for that which will need to be merged first.

**Comment by clalancette** [comment]
All right, this now depends on https://github.com/ros2/rcl/pull/1182 going in first.

**Comment by clalancette** [comment]
Pulls: https://github.com/ros2/rcutils/pull/478
Gist: https://gist.githubusercontent.com/clalancette/1e055d6a7e132f4fd947d2d7bb367895/raw/e7af239fbc2785887fc1e6ee1f32787191ab063f/ros2.repos
BUILD args:  --packages-above-and-dependencies rcutils
TEST args:  --packages-above rcutils
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14573
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21850/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16120/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1356/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22561/)

**Comment by clalancette** [comment]
All right, with the other fixes in, this is now clean.  Going ahead and merging this one, thanks for the review!
