### PR TITLE
Fix a leak in test_array_list.cpp

### LINKED ISSUE #148: Fix test_array_list leaks
```
Running main() from ../../../install-asan/gtest_vendor/src/gtest_vendor/src/gtest_main.cc
[==========] Running 31 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 19 tests from ArrayListTest
[ RUN      ] ArrayListTest.init_list_null_fails
[       OK ] ArrayListTest.init_list_null_fails (0 ms)
[ RUN      ] ArrayListTest.init_initial_capacity_zero_fails
[       OK ] ArrayListTest.init_initial_capacity_zero_fails (0 ms)
[ RUN      ] ArrayListTest.init_data_size_zero_fails
[       OK ] ArrayListTest.init_data_size_zero_fails (0 ms)
[ RUN      ] ArrayListTest.init_null_allocator_fails
[       OK ] ArrayListTest.init_null_allocator_fails (0 ms)
[ RUN      ] ArrayListTest.init_success
[       OK ] ArrayListTest.init_success (0 ms)
[ RUN      ] ArrayListTest.fini_list_null
[       OK ] ArrayListTest.fini_list_null (0 ms)
[ RUN      ] ArrayListTest.fini_list_not_initialized
[       OK ] ArrayListTest.fini_list_not_initialized (0 ms)
[ RUN      ] ArrayListTest.fini_success
[       OK ] ArrayListTest.fini_success (0 ms)
[ RUN      ] ArrayListTest.add_list_null_fails
[       OK ] ArrayListTest.add_list_null_fails (0 ms)
[ RUN      ] ArrayListTest.add_list_not_initialized_fails
[       OK ] ArrayListTest.add_list_not_initialized_fails (0 ms)
[ RUN      ] ArrayListTest.set_list_null_fails
[       OK ] ArrayListTest.set_list_null_fails (0 ms)
[ RUN      ] ArrayListTest.set_list_not_initialized_fails
[       OK ] ArrayListTest.set_list_not_initialized_fails (0 ms)
[ RUN      ] ArrayListTest.remove_list_null_fails
[       OK ] ArrayListTest.remove_list_null_fails (0 ms)
[ RUN      ] ArrayListTest.remove_list_not_initialized_fails
[       OK ] ArrayListTest.remove_list_not_initialized_fails (0 ms)
[ RUN      ] ArrayListTest.get_list_null_fails
[       OK ] ArrayListTest.get_list_null_fails (0 ms)
[ RUN      ] ArrayListTest.get_list_not_initialized_fails
[       OK ] ArrayListTest.get_list_not_initialized_fails (0 ms)
[ RUN      ] ArrayListTest.get_size_list_null_fails
[       OK ] ArrayListTest.get_size_list_null_fails (0 ms)
[ RUN      ] ArrayListTest.get_size_list_not_initialized_fails
[       OK ] ArrayListTest.get_size_list_not_initialized_fails (0 ms)
[ RUN      ] ArrayListTest.add_grow_capacity
[       OK ] ArrayListTest.add_grow_capacity (0 ms)
[----------] 19 tests from ArrayListTest (0 ms total)

[----------] 12 tests from ArrayListPreInitTest
[ RUN      ] ArrayListPreInitTest.add_data_null_fails
[       OK ] ArrayListPreInitTest.add_data_null_fails (0 ms)
[ RUN      ] ArrayListPreInitTest.add_success
[       OK ] ArrayListPreInitTest.add_success (0 ms)
[ RUN      ] ArrayListPreInitTest.set_data_null_fails
[       OK ] ArrayListPreInitTest.set_data_null_fails (0 ms)
[ RUN      ] ArrayListPreInitTest.set_data_index_oob_fails
[       OK ] ArrayListPreInitTest.set_data_index_oob_fails (0 ms)
[ RUN      ] ArrayListPreInitTest.set_success_changes_data
[       OK ] ArrayListPreInitTest.set_success_changes_data (0 ms)
[ RUN      ] ArrayListPreInitTest.remove_data_index_oob_fails
[       OK ] ArrayListPreInitTest.remove_data_index_oob_fails (0 ms)
[ RUN      ] ArrayListPreInitTest.remove_success_removes_from_list
[       OK ] ArrayListPreInitTest.remove_success_removes_from_list (0 ms)
[ RUN      ] ArrayListPreInitTest.get_data_index_oob_fails
[       OK ] ArrayListPreInitTest.get_data_index_oob_fails (0 ms)
[ RUN      ] ArrayListPreInitTest.get_data_success_returns_data
[       OK ] ArrayListPreInitTest.get_data_success_returns_data (0 ms)
[ RUN      ] ArrayListPreInitTest.get_size_size_null_fails
[       OK ] ArrayListPreInitTest.get_size_size_null_fails (0 ms)
[ RUN      ] ArrayListPreInitTest.get_size_increases_with_add
[       OK ] ArrayListPreInitTest.get_size_increases_with_add (0 ms)
[ RUN      ] ArrayListPreInitTest.remove_preserves_data_around_it
[       OK ] ArrayListPreInitTest.remove_preserves_data_around_it (0 ms)
[----------] 12 tests from ArrayListPreInitTest (0 ms total)

[----------] Global test environment tear-down
[==========] 31 tests from 2 test cases ran. (0 ms total)
[  PASSED  ] 31 tests.

=================================================================
==5522==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x7fce6828db50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7fce67f9fba5 in __default_allocate (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/install/rcutils/lib/librcutils.so+0x3ba5)
    #2 0x7fce67f9fe98 in rcutils_array_list_init (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/install/rcutils/lib/librcutils.so+0x3e98)
    #3 0x55a62186398c in ArrayListTest_init_success_Test::TestBody() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x1c98c)
    #4 0x55a6218f3769 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xac769)
    #5 0x55a6218e5491 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x9e491)
    #6 0x55a6218911ed in testing::Test::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4a1ed)
    #7 0x55a621892618 in testing::TestInfo::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4b618)
    #8 0x55a6218931bc in testing::TestCase::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4c1bc)
    #9 0x55a6218ae2cd in testing::internal::UnitTestImpl::RunAllTests() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x672cd)
    #10 0x55a6218f621c in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xaf21c)
    #11 0x55a6218e775a in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xa075a)
    #12 0x55a6218ab061 in testing::UnitTest::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x64061)
    #13 0x55a62187e5b0 in RUN_ALL_TESTS() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x375b0)
    #14 0x55a62187e4f6 in main (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x374f6)
    #15 0x7fce6740cb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x7fce6828db50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7fce67f9fba5 in __default_allocate (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/install/rcutils/lib/librcutils.so+0x3ba5)
    #2 0x7fce67f9fe98 in rcutils_array_list_init (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/install/rcutils/lib/librcutils.so+0x3e98)
    #3 0x55a62186f09c in ArrayListTest_add_grow_capacity_Test::TestBody() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x2809c)
    #4 0x55a6218f3769 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xac769)
    #5 0x55a6218e5491 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x9e491)
    #6 0x55a6218911ed in testing::Test::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4a1ed)
    #7 0x55a621892618 in testing::TestInfo::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4b618)
    #8 0x55a6218931bc in testing::TestCase::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4c1bc)
    #9 0x55a6218ae2cd in testing::internal::UnitTestImpl::RunAllTests() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x672cd)
    #10 0x55a6218f621c in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xaf21c)
    #11 0x55a6218e775a in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xa075a)
    #12 0x55a6218ab061 in testing::UnitTest::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x64061)
    #13 0x55a62187e5b0 in RUN_ALL_TESTS() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x375b0)
    #14 0x55a62187e4f6 in main (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x374f6)
    #15 0x7fce6740cb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7fce6828df40 in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdef40)
    #1 0x7fce67f9fbed in __default_reallocate (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/install/rcutils/lib/librcutils.so+0x3bed)
    #2 0x7fce67fa00dd in rcutils_array_list_increase_capacity (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/install/rcutils/lib/librcutils.so+0x40dd)
    #3 0x7fce67fa0214 in rcutils_array_list_add (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/install/rcutils/lib/librcutils.so+0x4214)
    #4 0x55a62186f3cd in ArrayListTest_add_grow_capacity_Test::TestBody() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x283cd)
    #5 0x55a6218f3769 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xac769)
    #6 0x55a6218e5491 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x9e491)
    #7 0x55a6218911ed in testing::Test::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4a1ed)
    #8 0x55a621892618 in testing::TestInfo::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4b618)
    #9 0x55a6218931bc in testing::TestCase::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4c1bc)
    #10 0x55a6218ae2cd in testing::internal::UnitTestImpl::RunAllTests() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x672cd)
    #11 0x55a6218f621c in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xaf21c)
    #12 0x55a6218e775a in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xa075a)
    #13 0x55a6218ab061 in testing::UnitTest::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x64061)
    #14 0x55a62187e5b0 in RUN_ALL_TESTS() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x375b0)
    #15 0x55a62187e4f6 in main (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x374f6)
    #16 0x7fce6740cb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x7fce6828db50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7fce67f9fba5 in __default_allocate (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/install/rcutils/lib/librcutils.so+0x3ba5)
    #2 0x7fce67f9ff23 in rcutils_array_list_init (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/install/rcutils/lib/librcutils.so+0x3f23)
    #3 0x55a62186398c in ArrayListTest_init_success_Test::TestBody() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x1c98c)
    #4 0x55a6218f3769 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xac769)
    #5 0x55a6218e5491 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x9e491)
    #6 0x55a6218911ed in testing::Test::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4a1ed)
    #7 0x55a621892618 in testing::TestInfo::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4b618)
    #8 0x55a6218931bc in testing::TestCase::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4c1bc)
    #9 0x55a6218ae2cd in testing::internal::UnitTestImpl::RunAllTests() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x672cd)
    #10 0x55a6218f621c in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xaf21c)
    #11 0x55a6218e775a in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xa075a)
    #12 0x55a6218ab061 in testing::UnitTest::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x64061)
    #13 0x55a62187e5b0 in RUN_ALL_TESTS() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x375b0)
    #14 0x55a62187e4f6 in main (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x374f6)
    #15 0x7fce6740cb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

SUMMARY: AddressSanitizer: 280 byte(s) leaked in 4 allocation(s).
```

### PR DESCRIPTION
**Pull request by thomas-moulard**
Before this change, test_array_list ASAN was reporting
280 bytes leaked in 4 allocations. After this patch
is applied, test_array_list does not emit any ASAN related
warning anymore.

Fixes #148

Signed-off-by: Thomas Moulard <tmoulard@amazon.com>

### CODE REVIEW

**Comment by thomas-moulard** [comment]
Before:
```
Running main() from ../../../install-asan/gtest_vendor/src/gtest_vendor/src/gtest_main.cc
[==========] Running 31 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 19 tests from ArrayListTest
[ RUN      ] ArrayListTest.init_list_null_fails
[       OK ] ArrayListTest.init_list_null_fails (0 ms)
[ RUN      ] ArrayListTest.init_initial_capacity_zero_fails
[       OK ] ArrayListTest.init_initial_capacity_zero_fails (0 ms)
[ RUN      ] ArrayListTest.init_data_size_zero_fails
[       OK ] ArrayListTest.init_data_size_zero_fails (0 ms)
[ RUN      ] ArrayListTest.init_null_allocator_fails
[       OK ] ArrayListTest.init_null_allocator_fails (0 ms)
[ RUN      ] ArrayListTest.init_success
[       OK ] ArrayListTest.init_success (0 ms)
[ RUN      ] ArrayListTest.fini_list_null
[       OK ] ArrayListTest.fini_list_null (0 ms)
[ RUN      ] ArrayListTest.fini_list_not_initialized
[       OK ] ArrayListTest.fini_list_not_initialized (0 ms)
[ RUN      ] ArrayListTest.fini_success
[       OK ] ArrayListTest.fini_success (0 ms)
[ RUN      ] ArrayListTest.add_list_null_fails
[       OK ] ArrayListTest.add_list_null_fails (0 ms)
[ RUN      ] ArrayListTest.add_list_not_initialized_fails
[       OK ] ArrayListTest.add_list_not_initialized_fails (0 ms)
[ RUN      ] ArrayListTest.set_list_null_fails
[       OK ] ArrayListTest.set_list_null_fails (0 ms)
[ RUN      ] ArrayListTest.set_list_not_initialized_fails
[       OK ] ArrayListTest.set_list_not_initialized_fails (0 ms)
[ RUN      ] ArrayListTest.remove_list_null_fails
[       OK ] ArrayListTest.remove_list_null_fails (0 ms)
[ RUN      ] ArrayListTest.remove_list_not_initialized_fails
[       OK ] ArrayListTest.remove_list_not_initialized_fails (0 ms)
[ RUN      ] ArrayListTest.get_list_null_fails
[       OK ] ArrayListTest.get_list_null_fails (0 ms)
[ RUN      ] ArrayListTest.get_list_not_initialized_fails
[       OK ] ArrayListTest.get_list_not_initialized_fails (0 ms)
[ RUN      ] ArrayListTest.get_size_list_null_fails
[       OK ] ArrayListTest.get_size_list_null_fails (0 ms)
[ RUN      ] ArrayListTest.get_size_list_not_initialized_fails
[       OK ] ArrayListTest.get_size_list_not_initialized_fails (0 ms)
[ RUN      ] ArrayListTest.add_grow_capacity
[       OK ] ArrayListTest.add_grow_capacity (0 ms)
[----------] 19 tests from ArrayListTest (0 ms total)

[----------] 12 tests from ArrayListPreInitTest
[ RUN      ] ArrayListPreInitTest.add_data_null_fails
[       OK ] ArrayListPreInitTest.add_data_null_fails (0 ms)
[ RUN      ] ArrayListPreInitTest.add_success
[       OK ] ArrayListPreInitTest.add_success (0 ms)
[ RUN      ] ArrayListPreInitTest.set_data_null_fails
[       OK ] ArrayListPreInitTest.set_data_null_fails (0 ms)
[ RUN      ] ArrayListPreInitTest.set_data_index_oob_fails
[       OK ] ArrayListPreInitTest.set_data_index_oob_fails (0 ms)
[ RUN      ] ArrayListPreInitTest.set_success_changes_data
[       OK ] ArrayListPreInitTest.set_success_changes_data (0 ms)
[ RUN      ] ArrayListPreInitTest.remove_data_index_oob_fails
[       OK ] ArrayListPreInitTest.remove_data_index_oob_fails (0 ms)
[ RUN      ] ArrayListPreInitTest.remove_success_removes_from_list
[       OK ] ArrayListPreInitTest.remove_success_removes_from_list (0 ms)
[ RUN      ] ArrayListPreInitTest.get_data_index_oob_fails
[       OK ] ArrayListPreInitTest.get_data_index_oob_fails (0 ms)
[ RUN      ] ArrayListPreInitTest.get_data_success_returns_data
[       OK ] ArrayListPreInitTest.get_data_success_returns_data (0 ms)
[ RUN      ] ArrayListPreInitTest.get_size_size_null_fails
[       OK ] ArrayListPreInitTest.get_size_size_null_fails (0 ms)
[ RUN      ] ArrayListPreInitTest.get_size_increases_with_add
[       OK ] ArrayListPreInitTest.get_size_increases_with_add (0 ms)
[ RUN      ] ArrayListPreInitTest.remove_preserves_data_around_it
[       OK ] ArrayListPreInitTest.remove_preserves_data_around_it (0 ms)
[----------] 12 tests from ArrayListPreInitTest (0 ms total)

[----------] Global test environment tear-down
[==========] 31 tests from 2 test cases ran. (0 ms total)
[  PASSED  ] 31 tests.

=================================================================
==5522==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x7fce6828db50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7fce67f9fba5 in __default_allocate (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/install/rcutils/lib/librcutils.so+0x3ba5)
    #2 0x7fce67f9fe98 in rcutils_array_list_init (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/install/rcutils/lib/librcutils.so+0x3e98)
    #3 0x55a62186398c in ArrayListTest_init_success_Test::TestBody() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x1c98c)
    #4 0x55a6218f3769 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xac769)
    #5 0x55a6218e5491 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x9e491)
    #6 0x55a6218911ed in testing::Test::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4a1ed)
    #7 0x55a621892618 in testing::TestInfo::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4b618)
    #8 0x55a6218931bc in testing::TestCase::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4c1bc)
    #9 0x55a6218ae2cd in testing::internal::UnitTestImpl::RunAllTests() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x672cd)
    #10 0x55a6218f621c in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xaf21c)
    #11 0x55a6218e775a in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xa075a)
    #12 0x55a6218ab061 in testing::UnitTest::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x64061)
    #13 0x55a62187e5b0 in RUN_ALL_TESTS() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x375b0)
    #14 0x55a62187e4f6 in main (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x374f6)
    #15 0x7fce6740cb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x7fce6828db50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7fce67f9fba5 in __default_allocate (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/install/rcutils/lib/librcutils.so+0x3ba5)
    #2 0x7fce67f9fe98 in rcutils_array_list_init (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/install/rcutils/lib/librcutils.so+0x3e98)
    #3 0x55a62186f09c in ArrayListTest_add_grow_capacity_Test::TestBody() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x2809c)
    #4 0x55a6218f3769 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xac769)
    #5 0x55a6218e5491 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x9e491)
    #6 0x55a6218911ed in testing::Test::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4a1ed)
    #7 0x55a621892618 in testing::TestInfo::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4b618)
    #8 0x55a6218931bc in testing::TestCase::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4c1bc)
    #9 0x55a6218ae2cd in testing::internal::UnitTestImpl::RunAllTests() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x672cd)
    #10 0x55a6218f621c in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xaf21c)
    #11 0x55a6218e775a in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xa075a)
    #12 0x55a6218ab061 in testing::UnitTest::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x64061)
    #13 0x55a62187e5b0 in RUN_ALL_TESTS() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x375b0)
    #14 0x55a62187e4f6 in main (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x374f6)
    #15 0x7fce6740cb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7fce6828df40 in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdef40)
    #1 0x7fce67f9fbed in __default_reallocate (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/install/rcutils/lib/librcutils.so+0x3bed)
    #2 0x7fce67fa00dd in rcutils_array_list_increase_capacity (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/install/rcutils/lib/librcutils.so+0x40dd)
    #3 0x7fce67fa0214 in rcutils_array_list_add (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/install/rcutils/lib/librcutils.so+0x4214)
    #4 0x55a62186f3cd in ArrayListTest_add_grow_capacity_Test::TestBody() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x283cd)
    #5 0x55a6218f3769 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xac769)
    #6 0x55a6218e5491 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x9e491)
    #7 0x55a6218911ed in testing::Test::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4a1ed)
    #8 0x55a621892618 in testing::TestInfo::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4b618)
    #9 0x55a6218931bc in testing::TestCase::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4c1bc)
    #10 0x55a6218ae2cd in testing::internal::UnitTestImpl::RunAllTests() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x672cd)
    #11 0x55a6218f621c in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xaf21c)
    #12 0x55a6218e775a in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xa075a)
    #13 0x55a6218ab061 in testing::UnitTest::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x64061)
    #14 0x55a62187e5b0 in RUN_ALL_TESTS() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x375b0)
    #15 0x55a62187e4f6 in main (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x374f6)
    #16 0x7fce6740cb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x7fce6828db50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7fce67f9fba5 in __default_allocate (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/install/rcutils/lib/librcutils.so+0x3ba5)
    #2 0x7fce67f9ff23 in rcutils_array_list_init (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/install/rcutils/lib/librcutils.so+0x3f23)
    #3 0x55a62186398c in ArrayListTest_init_success_Test::TestBody() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x1c98c)
    #4 0x55a6218f3769 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xac769)
    #5 0x55a6218e5491 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x9e491)
    #6 0x55a6218911ed in testing::Test::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4a1ed)
    #7 0x55a621892618 in testing::TestInfo::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4b618)
    #8 0x55a6218931bc in testing::TestCase::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x4c1bc)
    #9 0x55a6218ae2cd in testing::internal::UnitTestImpl::RunAllTests() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x672cd)
    #10 0x55a6218f621c in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xaf21c)
    #11 0x55a6218e775a in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0xa075a)
    #12 0x55a6218ab061 in testing::UnitTest::Run() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x64061)
    #13 0x55a62187e5b0 in RUN_ALL_TESTS() (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x375b0)
    #14 0x55a62187e4f6 in main (/home/ANT.AMAZON.COM/tmoulard/ros2_ws/build-asan/rcutils/test_array_list+0x374f6)
    #15 0x7fce6740cb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

SUMMARY: AddressSanitizer: 280 byte(s) leaked in 4 allocation(s).
```

After:
```
Running main() from ../../../install-asan/gtest_vendor/src/gtest_vendor/src/gtest_main.cc
[==========] Running 31 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 19 tests from ArrayListTest
[ RUN      ] ArrayListTest.init_list_null_fails
[       OK ] ArrayListTest.init_list_null_fails (0 ms)
[ RUN      ] ArrayListTest.init_initial_capacity_zero_fails
[       OK ] ArrayListTest.init_initial_capacity_zero_fails (0 ms)
[ RUN      ] ArrayListTest.init_data_size_zero_fails
[       OK ] ArrayListTest.init_data_size_zero_fails (0 ms)
[ RUN      ] ArrayListTest.init_null_allocator_fails
[       OK ] ArrayListTest.init_null_allocator_fails (0 ms)
[ RUN      ] ArrayListTest.init_success
[       OK ] ArrayListTest.init_success (0 ms)
[ RUN      ] ArrayListTest.fini_list_null
[       OK ] ArrayListTest.fini_list_null (0 ms)
[ RUN      ] ArrayListTest.fini_list_not_initialized
[       OK ] ArrayListTest.fini_list_not_initialized (0 ms)
[ RUN      ] ArrayListTest.fini_success
[       OK ] ArrayListTest.fini_success (0 ms)
[ RUN      ] ArrayListTest.add_list_null_fails
[       OK ] ArrayListTest.add_list_null_fails (0 ms)
[ RUN      ] ArrayListTest.add_list_not_initialized_fails
[       OK ] ArrayListTest.add_list_not_initialized_fails (0 ms)
[ RUN      ] ArrayListTest.set_list_null_fails
[       OK ] ArrayListTest.set_list_null_fails (0 ms)
[ RUN      ] ArrayListTest.set_list_not_initialized_fails
[       OK ] ArrayListTest.set_list_not_initialized_fails (0 ms)
[ RUN      ] ArrayListTest.remove_list_null_fails
[       OK ] ArrayListTest.remove_list_null_fails (0 ms)
[ RUN      ] ArrayListTest.remove_list_not_initialized_fails
[       OK ] ArrayListTest.remove_list_not_initialized_fails (0 ms)
[ RUN      ] ArrayListTest.get_list_null_fails
[       OK ] ArrayListTest.get_list_null_fails (0 ms)
[ RUN      ] ArrayListTest.get_list_not_initialized_fails
[       OK ] ArrayListTest.get_list_not_initialized_fails (0 ms)
[ RUN      ] ArrayListTest.get_size_list_null_fails
[       OK ] ArrayListTest.get_size_list_null_fails (0 ms)
[ RUN      ] ArrayListTest.get_size_list_not_initialized_fails
[       OK ] ArrayListTest.get_size_list_not_initialized_fails (0 ms)
[ RUN      ] ArrayListTest.add_grow_capacity
[       OK ] ArrayListTest.add_grow_capacity (0 ms)
[----------] 19 tests from ArrayListTest (0 ms total)

[----------] 12 tests from ArrayListPreInitTest
[ RUN      ] ArrayListPreInitTest.add_data_null_fails
[       OK ] ArrayListPreInitTest.add_data_null_fails (0 ms)
[ RUN      ] ArrayListPreInitTest.add_success
[       OK ] ArrayListPreInitTest.add_success (0 ms)
[ RUN      ] ArrayListPreInitTest.set_data_null_fails
[       OK ] ArrayListPreInitTest.set_data_null_fails (0 ms)
[ RUN      ] ArrayListPreInitTest.set_data_index_oob_fails
[       OK ] ArrayListPreInitTest.set_data_index_oob_fails (0 ms)
[ RUN      ] ArrayListPreInitTest.set_success_changes_data
[       OK ] ArrayListPreInitTest.set_success_changes_data (0 ms)
[ RUN      ] ArrayListPreInitTest.remove_data_index_oob_fails
[       OK ] ArrayListPreInitTest.remove_data_index_oob_fails (0 ms)
[ RUN      ] ArrayListPreInitTest.remove_success_removes_from_list
[       OK ] ArrayListPreInitTest.remove_success_removes_from_list (0 ms)
[ RUN      ] ArrayListPreInitTest.get_data_index_oob_fails
[       OK ] ArrayListPreInitTest.get_data_index_oob_fails (0 ms)
[ RUN      ] ArrayListPreInitTest.get_data_success_returns_data
[       OK ] ArrayListPreInitTest.get_data_success_returns_data (0 ms)
[ RUN      ] ArrayListPreInitTest.get_size_size_null_fails
[       OK ] ArrayListPreInitTest.get_size_size_null_fails (0 ms)
[ RUN      ] ArrayListPreInitTest.get_size_increases_with_add
[       OK ] ArrayListPreInitTest.get_size_increases_with_add (0 ms)
[ RUN      ] ArrayListPreInitTest.remove_preserves_data_around_it
[       OK ] ArrayListPreInitTest.remove_preserves_data_around_it (0 ms)
[----------] 12 tests from ArrayListPreInitTest (0 ms total)

[----------] Global test environment tear-down
[==========] 31 tests from 2 test cases ran. (0 ms total)
[  PASSED  ] 31 tests.
```

**Comment by thomas-moulard** [comment]
@wjwwood another one fixing leaks in tests

**Comment by thomas-moulard** [comment]
I tried to apply your comments from the other PR here. Note that the situation is bit different as there already was a fixture to initialize the data structure.

I kept the pattern in the TearDown allowing `_fini` to fail under the principle that if we test fail (and the list never gets initialized), it's not a reason to have the TearDown failing too. This adds noise and make debugging more difficult (hard to differentiate the real problem from a minor side effect).

File: test/test_array_list.cpp [hunk 1]
```diff
@@ -28,38 +28,36 @@ class ArrayListTest : public ::testing::Test
...
   }
 
   void TearDown() override
   {
-    rcutils_ret_t ret = rcutils_array_list_fini(&list);
-    EXPECT_EQ(RCUTILS_RET_OK, ret) << rcutils_get_error_string().str;
+    // If the test fails, the test may exit before the list has been initialized
+    // so we allow rcutils_array_list_fini to fail if the list is not initialized.
+    const rcutils_ret_t ret = rcutils_array_list_fini(&list);
+    EXPECT_TRUE(ret == RCUTILS_RET_OK || ret == RCUTILS_RET_NOT_INITIALIZED);
```
Comment (wjwwood) [inline test/test_array_list.cpp]: I still disagree about this, what I'd prefer to see is that you ensure fini is called in any test that does call init. You can accomplish this (as we do in other places in our tests) by using a "scope exit" (there's a header-only implementation provided by `osrf_testing_tools_cpp`), like so:

```c++
rcutils_ret_t ret = rcutils_array_list_init(&list, ...);
ASSERT_EQ(RCUTILS_RET_OK, ret) << rcutils_get_error_string().str;
rcutils_reset_error();
OSRF_TESTING_TOOLS_CPP_SCOPE_EXIT({
  EXPECT_EQ(RCUTILS_RET_OK, rcutils_array_list_fini(&list)) << rcutils_get_error_string().str;
  rcutils_reset_error();
});
```

If you don't reach the scope exit line, the fini will not run, but if you do reach it you know it will get called when the test function exits (for any reason) and you also know that the init was successfully called before it.

Comment (thomas-moulard) [reply test/test_array_list.cpp]: I understand your suggestion and I applied it in the other PR.

In this case, IIUC your suggestion would mean getting rid of the second pre-existing fixture which is fine but would mean moving back init calls in the test cases everywhere (12 test cases) and as a consequence would expand the scope of this PR. Which strategy would you prefer? Either is fine for me.

Comment (wjwwood) [reply test/test_array_list.cpp]: I think the `ArrayListPreInitTest` is ok (except it should use ASSERT instead in the setup) because it init's in the setup and fini's in the teardown, so they're matched. I don't think it (or the tests that use it) need to be touched.

If any test does not use it, for whatever reason, and does the init themselves then they should use the scope exit to ensure a fini when it is needed.

File: test/test_array_list.cpp [hunk 2]
```diff
@@ -28,38 +28,36 @@ class ArrayListTest : public ::testing::Test
...
 {
 protected:
   void SetUp() override
   {
-    allocator = rcutils_get_default_allocator();
-    list = rcutils_get_zero_initialized_array_list();
-    rcutils_ret_t ret = rcutils_array_list_init(&list, 2, sizeof(uint32_t), &allocator);
+    ArrayListTest::SetUp();
+    const rcutils_ret_t ret = rcutils_array_list_init(&list, 2, sizeof(uint32_t), &allocator);
     EXPECT_EQ(RCUTILS_RET_OK, ret) << rcutils_get_error_string().str;
```
Comment (wjwwood) [inline test/test_array_list.cpp]: This should be an ASSERT, because the test shouldn't even run if the init fails here.

Comment (thomas-moulard) [reply test/test_array_list.cpp]: Done!

File: test/test_array_list.cpp (hunk 1 above)
Comment (thomas-moulard) [reply test/test_array_list.cpp]: :+1:

**Comment by thomas-moulard** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/6679/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2998/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5487/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6509/)

**Comment by thomas-moulard** [comment]
I think I fixed everything and it should be OK to merge if CI is green.

**Comment by thomas-moulard** [comment]
@wjwwood Should be ok to merge!

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/introducing-ros2-sanitizer-report-and-analysis/9287/1
