### PR TITLE
Check SIZE_MAX for array initialization.

### LINKED ISSUE #2252: make_empty_serialized_message() cannot handle extremely large sizes, causing a crash
## Description
When make_empty_serialized_message() handles an extremely large buffer size, the function internally calls rcutils_uint8_array_init(), which directly attempts to allocate an enormous amount of memory, leading to a crash.

### Expected Behavior
no crash

### Actual Behavior
crash

### Test Case
```cpp
#include <gmock/gmock.h>
#include <memory>
#include "rosbag2_storage/ros_helper.hpp"
using namespace ::testing;  // NOLINT

TEST(ros_helper, test1) {
  try {
    auto empty_serialized_message = rosbag2_storage::make_empty_serialized_message(std::numeric_limits<std::size_t>::max());
    ASSERT_THAT(empty_serialized_message->buffer_length, Eq(0u));
    ASSERT_THAT(empty_serialized_message->buffer_capacity, Eq(std::numeric_limits<std::size_t>::max()));
  } catch (const std::exception& e) {
    ASSERT_TRUE(std::string(e.what()).find("allocation failed") != std::string::npos);
  }
}
```

### Output
```markdown
[ RUN      ] ros_helper.test1
=================================================================
==8137==ERROR: AddressSanitizer: requested allocation size 0xffffffffffffffff (0x800 after adjustments for alignment, red zones etc.) exceeds maximum supported size of 0x10000000000 (thread T0)
    #0 0x7feb82afd9c7 in malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7feb8117b0cc in __default_allocate (/home/shangzh/ros2_jazzy/install/rcutils/lib/librcutils.so+0x60cc) (BuildId: 47470fc0f3cc7c03a11a022d1a45f220e5c43954)
    #2 0x7feb8118a5d4 in rcutils_uint8_array_init (/home/shangzh/ros2_jazzy/install/rcutils/lib/librcutils.so+0x155d4) (BuildId: 47470fc0f3cc7c03a11a022d1a45f220e5c43954)
    #3 0x7feb829627f7 in rosbag2_storage::make_empty_serialized_message(unsigned long) (/home/shangzh/ros2_jazzy/install/rosbag2_storage/lib/librosbag2_storage.so+0x1407f7) (BuildId: 9356fba64f173b3892930a1219d31e451df57aea)
    #4 0x5767e659d47e in ros_helper_test1_Test::TestBody() (/home/shangzh/rosbag2_ws/build/rosbag2_storage/test_ros_helper+0xaf47e) (BuildId: 756766f591388170229c1aeca93a6c97708ea4bb)
    #5 0x5767e66423c7 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_storage/test_ros_helper+0x1543c7) (BuildId: 756766f591388170229c1aeca93a6c97708ea4bb)
    #6 0x5767e662f81b in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_storage/test_ros_helper+0x14181b) (BuildId: 756766f591388170229c1aeca93a6c97708ea4bb)
    #7 0x5767e65d5c7b in testing::Test::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_storage/test_ros_helper+0xe7c7b) (BuildId: 756766f591388170229c1aeca93a6c97708ea4bb)
    #8 0x5767e65d7457 in testing::TestInfo::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_storage/test_ros_helper+0xe9457) (BuildId: 756766f591388170229c1aeca93a6c97708ea4bb)
    #9 0x5767e65d87b0 in testing::TestSuite::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_storage/test_ros_helper+0xea7b0) (BuildId: 756766f591388170229c1aeca93a6c97708ea4bb)
    #10 0x5767e65ff4db in testing::internal::UnitTestImpl::RunAllTests() (/home/shangzh/rosbag2_ws/build/rosbag2_storage/test_ros_helper+0x1114db) (BuildId: 756766f591388170229c1aeca93a6c97708ea4bb)
    #11 0x5767e6645822 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_storage/test_ros_helper+0x157822) (BuildId: 756766f591388170229c1aeca93a6c97708ea4bb)
    #12 0x5767e6632ab8 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_storage/test_ros_helper+0x144ab8) (BuildId: 756766f591388170229c1aeca93a6c97708ea4bb)
    #13 0x5767e65fbae5 in testing::UnitTest::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_storage/test_ros_helper+0x10dae5) (BuildId: 756766f591388170229c1aeca93a6c97708ea4bb)
    #14 0x5767e65a5f86 in RUN_ALL_TESTS() (/home/shangzh/rosbag2_ws/build/rosbag2_storage/test_ros_helper+0xb7f86) (BuildId: 756766f591388170229c1aeca93a6c97708ea4bb)
    #15 0x5767e65a5ed2 in main (/home/shangzh/rosbag2_ws/build/rosbag2_storage/test_ros_helper+0xb7ed2) (BuildId: 756766f591388170229c1aeca93a6c97708ea4bb)
    #16 0x7feb80a2a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #17 0x7feb80a2a28a in __libc_start_main_impl ../csu/libc-start.c:360
    #18 0x5767e659d234 in _start (/home/shangzh/rosbag2_ws/build/rosbag2_storage/test_ros_helper+0xaf234) (BuildId: 756766f591388170229c1aeca93a6c97708ea4bb)

==8137==HINT: if you don't care about these errors you may set allocator_may_return_null=1
SUMMARY: AddressSanitizer: allocation-size-too-big ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69 in malloc
==8137==ABORTING
```

## System (please complete the following information)
OS: ubuntu 24.04
ROS 2 Distro: ros 2 jazzy
Install Method: source
Version: ros 2 jazzy
build options: --mixin asan-gcc

### PR DESCRIPTION
**Pull request by fujitatomoya**
## Description

Fixes https://github.com/ros2/rosbag2/issues/2252

### Is this user-facing behavior change?

No

### Did you use Generative AI?

No

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
@ahcorde can you take a look?

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
Pulls: ros2/rcutils#527
Gist: https://gist.githubusercontent.com/ahcorde/193bf2950049f06426159dcd54d5123f/raw/bb63328bf1a3cc2da6ab60afbec5869bb4713077/ros2.repos
BUILD args:  --packages-above-and-dependencies rcutils
TEST args:  --packages-above rcutils
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/17751
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/26499/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20126/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/6267/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26201/)

**Review by ahcorde — CHANGES_REQUESTED** [review]
I can see some new test errors

File: src/uint8_array.c [hunk 1]
```diff
@@ -36,6 +38,12 @@ rcutils_uint8_array_init(
   uint8_array->allocator = *allocator;
 
   if (buffer_capacity > 0lu) {
+    if (buffer_capacity >= SIZE_MAX) {
+      RCUTILS_SET_ERROR_MSG("requested capacity for uint8_array too large");
+      uint8_array->buffer_capacity = 0lu;
+      uint8_array->buffer_length = 0lu;
+      return RCUTILS_RET_INVALID_ARGUMENT;
```
Comment (fujitatomoya) [inline src/uint8_array.c]: https://ci.ros2.org/job/ci_linux/26499/testReport/junit/rclcpp/TestSerializedMessage/failed_init_throws/, the upper layer expects this as bad alloc failure. to keep the consistency, i think we should change this into `RCUTILS_RET_BAD_ALLOC`.

Comment (fujitatomoya) [reply src/uint8_array.c]: https://github.com/ros2/rcutils/pull/527/commits/f37cffa6131154b01e8338dcd7527f7238c764a3 should fix the failures.

**Comment by fujitatomoya** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/26522/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20132/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/6288/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26207/)

**Comment by fujitatomoya** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/26571/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20142/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/6361/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26210/)

**Comment by fujitatomoya** [comment]
@ahcorde windows failures are not related to PR.

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport kilted jazzy humble
