### PR TITLE
getprogname() is the correct API to use on Android.

### LINKED ISSUE #159: Cross compilation rcutils with Android NDK
Cross compiling rcutils with Clang/Android NDK (Android NDK / 19.2.5345600) 
results in following compilation error:

```
Scanning dependencies of target rcutils
[  4%] Building C object CMakeFiles/rcutils.dir/src/process.c.o
/home/EU/dekoehlr/work/ros2_core_ws/src/ros2/rcutils/src/process.c:53:26: error: use of undeclared identifier 'program_invocation_name'
  const char * appname = program_invocation_name;
                         ^
1 error generated.
CMakeFiles/rcutils.dir/build.make:332: recipe for target 'CMakeFiles/rcutils.dir/src/process.c.o' failed
make[2]: *** [CMakeFiles/rcutils.dir/src/process.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/rcutils.dir/all' failed
make[1]: *** [CMakeFiles/rcutils.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

As possible fix for this issue is to check for the  `__clang__` flag and use `getprogname()` instead of `program_invocation_name` specific to GCC/glibc.

```diff --git a/src/process.c b/src/process.c
index 08122de..fd77318 100644
--- a/src/process.c
+++ b/src/process.c
@@ -47,7 +47,7 @@ char * rcutils_get_executable_name(rcutils_allocator_t allocator)
   RCUTILS_CHECK_ALLOCATOR_WITH_MSG(
     &allocator, "invalid allocator", return NULL);
 
-#if defined __APPLE__
+#if defined __APPLE__ || __clang__
   const char * appname = getprogname();
 #elif defined __GNUC__
   const char * appname = program_invocation_name;
```

The script to reproduce the results is as follows:
```bash
#!/usr/env bash
#
# ROS2 Cross compiler build setup for Android SDK
#
# Prerequisites: 
# - installed Android NDK and cmake build tool addons.

export WORK_DIR=$HOME/work
export ROS2_WORKSPACE=$WORK_DIR/ros2_core_ws

# Provide Android SDK location
export JAVA_HOME=$HOME/local/android-studio/jre
export ANDROID_SDK=$HOME/local/android-sdk
export ANDROID_NDK=$HOME/local/android-sdk/ndk-bundle

export PATH=$ANDROID_SDK/tools/bin:${PATH}
export PATH=$ANDROID_SDK/platform-tools:${PATH}

# Android build toolchain
export ANDROID_ABI=armeabi-v7a
export ANDROID_NATIVE_API_LEVEL=android-21
export ANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-clang
export ANDROID_STL=c++_shared

# Download and install ROS2 sources
mkdir -p $ROS2_WORKSPACE
cd $ROS2_WORKSPACE
if [ ! -d src ]; then
  mkdir src
  wget -nc https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
  vcs import src < ros2.repos

  # Patch rcutils/src/process.c to support compilation with clang
  echo -e "50c50\n< #if defined __APPLE__\n---\n> #if defined __APPLE__ || __clang__" | patch src/ros2/rcutils/src/process.c
fi

# Partition packages into host and device build
# Note: Amend index is dependency of rclcpp_components - do not build for host.
AMENT_LINT=$(echo ament_{lint_common,lint_auto,lint_cmake,flake8,pep257,copyright})
AMENT_CMAKE=$(echo ament_cmake ament_cmake_{core,test,gmock,gtest,pytest,libraries,nose,python,pytest})
AMENT_INDEX="ament_index_python"

PKG_AMENT="${AMENT_CMAKE} ${AMENT_LINT} ${AMENT_INDEX} ament_cmake_ros ament_package ament_pclint ament_clang_format osrf_pycommon uncrustify_vendor osrf_testing_tools_cpp"
PKG_PYTHON="python_cmake_module rosidl_generator_py rclpy rosidl_runtime_py launch launch_ros launch_testing_ament_cmake"
PKG_EXTRAS="intra_process_demo orocos_kdl rclpy resource_retriever tf2_ros libcurl_vendor tinyxml2_vendor tinyxml_vendor"
PKG_CONNEXT="rosidl_typesupport_connext_c rosidl_typesupport_connext_cpp rmw_connext_cpp rmw_connext_shared_cpp" 
PKG_OPENSPLICE="rosidl_typesupport_opensplice_c rmw_opensplice_cpp rosidl_typesupport_opensplice_cpp"

# Ignore packages which cannot be build on target device
PKG_IGNORE="rcl_logging_log4cxx  ${PKG_PYTHON} ${PKG_EXTRAS} ${PKG_CONNEXT} ${PKG_OPENSPLICE} ${PKG_AMENT}"
PKG_EXAMPLES=$(echo examples_rclcpp_minimal_{action_client,action_server,client,composition,publisher,subscriber,service,timer})
PKG_TARGET="${PKG_EXAMPLES} ament_index_cpp composition demo_nodes_cpp_native lifecycle logging_demo"

echo "* Host build of Ament:"
colcon build --symlink-install \
  --build-base build/host \
  --install-base install/host \
  --cmake-clean-cache \
  --packages-skip-build \
  --packages-up-to ${PKG_AMENT}

source install/host/local_setup.bash
  
echo "* Device build of ROS2:"
colcon build --symlink-install  \
  --build-base build/device \
  --install-base install/device \
  --packages-up-to ${PKG_TARGET} \
  --packages-ignore ${PKG_IGNORE} \
  --cmake-clean-cache \
  --cmake-args \
    --no-warn-unused-cli \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake \
    -DANDROID_NATIVE_API_LEVEL=${ANDROID_NATIVE_API_LEVEL} \
    -DANDROID_TOOLCHAIN_NAME=${ANDROID_TOOLCHAIN_NAME} \
    -DANDROID_STL=${ANDROID_STL} \
    -DANDROID_ABI=${ANDROID_ABI} \
    -DANDROID_NDK=${ANDROID_NDK} \
    -DTHIRDPARTY=ON \
    -DCOMPILE_EXAMPLES=OFF \
    -DBUILD_TESTING=OFF \
    -DCMAKE_FIND_ROOT_PATH="$ROS2_WORKSPACE/install/host;$ROS2_WORKSPACE/install/device" \
    -DRCL_LOGGING_IMPLEMENTATION=rcl_logging_noop
```

Besides this minor issue, I was able to cross compile the core components of ROS2 on Android. Keep up the good work!

Best regards,

Roderick

### PR DESCRIPTION
**Pull request by clalancette**
While we are here, also fix the __CYGWIN__ macro, which was
missing the final two underscores.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

This should fix #159 , though I haven't been able to test that myself.  @roderick-koehle , this is a different solution than you proposed, but I think is more accurate.  Please give it a test and let me know if it fixes the issue for you.

### CODE REVIEW

File: src/process.c [hunk 1]
```diff
@@ -47,11 +47,11 @@ char * rcutils_get_executable_name(rcutils_allocator_t allocator)
   RCUTILS_CHECK_ALLOCATOR_WITH_MSG(
     &allocator, "invalid allocator", return NULL);
 
-#if defined __APPLE__
+#if defined __APPLE__ || defined __ANDROID__
   const char * appname = getprogname();
 #elif defined __GNUC__
   const char * appname = program_invocation_name;
-#elif defined _WIN32 || defined __CYGWIN
+#elif defined _WIN32 || defined __CYGWIN__
```
Comment (dirk-thomas) [inline src/process.c]: The same fix is needed in line 89.

Comment (clalancette) [reply src/process.c]: Good call. Fixed in 854a885

**Comment by clalancette** [comment]
> The patch looks good to me.

Thanks.

> Not sure if you want to wait for the reporter to confirm it works for them though...

Yeah, I'll probably wait a bit for some confirmation.

**Comment by dirk-thomas** [comment]
@clalancette What is the status of this PR?

**Comment by clalancette** [comment]
> @clalancette What is the status of this PR?

I'm still waiting on confirmation from the original reporter.  On the other hand, this really shouldn't break anything on existing platforms, so I think we can go forward with it.  Here's a CI run up to rcutils to make sure things are good on all platforms; assuming it is green I'll merge.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7260/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3440/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5939/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7073/)

**Comment by roderick-koehle** [comment]
This fix is fine, from my side the issue can be closed.
